name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "30 0 * * 6"
  workflow_dispatch:

jobs:
  buildntest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Update PlatformIO
      run: |
        pio update
        pio lib update
    - name: Perform development build
      run: make
    - name: Run tests
      run: make test
    - name: Perform release build
      run: make release
